### ISSUE TITLE
Datentypen bei Elementen im LogicalModel

### ISSUE THREAD

**Issue by vabishaa** [medizininformatik-initiative/kerndatensatzmodul-person#11]
@MiriamHue : Im Logical Model der Version 2.0.0-ballot2 wurde bei fast allen Datenelementen "string" als Datentyp hinterlegt. In der vorherigen Version (1.0.16) wurden bereits spezifischere Datentypen hinterlegt. Wird dies noch aktualisiert oder gibt es einen bestimmten Grund warum diese nicht übernommen wurden?

**Comment by alexzautke** [comment]
Die Datentypen sollte noch angepasst werden.
