### ISSUE TITLE
Ungültige JSON-Struktur der Datei cps-mii-person-capabilitystatement.json

### ISSUE THREAD

**Issue by jonasrenz** [medizininformatik-initiative/kerndatensatzmodul-person#13]
Nach dem Einfügen von dem Package Modul Person mit der Version 2.0.0-ballot2 kam folgender Fehler:

`2023-07-05 11:35:30.814 ERROR Module persistence_r4 failed to start with error: ca.cdr.api.module.StartupFailedException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'packageRegistryLoader': Invocation of init method failed; nested exception is ca.uhn.fhir.parser.DataFormatException: HAPI-1861: Failed to parse JSON encoded FHIR content: Unexpected character (']' (code 93)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false') at [Source: UNKNOWN; line: 695, column: 12]`

Ich habe die Datei lokal repariert. In Zeile 694, Spalte 15, Pos. 24754 ist ein Kommazeichen ',' zu viel.

**Comment by alexzautke** [comment]
Fixed in https://github.com/medizininformatik-initiative/kerndatensatzmodul-person/commit/1388819656469de81d726ee32125e2c7393236ec
