### ISSUE TITLE
Quartalsrundung bei Geburts- und Todesdatum

### ISSUE THREAD

**Issue by alexzautke** [medizininformatik-initiative/kerndatensatzmodul-person#19]
Der IG gibt bei Geburts- und Todesdatum vor, das Datum auf "den ersten Monat des nächsten Quartals auf-/abzurunden". Wörtlich genommen würde ein gegebenes Datum "31.12.1999" dann zu "2000-01" statt zu "1999-10" gerundet werden.
Dies hätte gegenüber einer durchgehenden Abrundung mehrere Nachteile:
Der tatsächliche Geburts- oder Todestag kann außerhalb des gemappten Quartals liegen
Nutzdaten, wie z.B. Laborwerte könnten vor einem gerundeten Geburtstag erfasst/datiert sein
Die Jahreszahl könnte sich wie in oben gezeigtem Beispiel ändern, was je nach Auswertung zu Verzerrung führen könnte
Es ist nicht intuitiv
Daher wäre (auch nach Absprache in der MIRACUM/DIFUTURE-ETL-Entwickler-Runde) eine Änderung der Formulierung im Profil auf stets "abrunden" wünschenswert.

**Comment by alexzautke** [comment]
Die Constraints "GeburtsdatumRundenAufQuartal", "TodesdatumKeineZeitangabe", "PostleitzahlEinschraenkung" werden entfernt. Alle 0..0 Constraints werden aufgehoben, jedoch werden alle Pflichtfelder aus dem "Patient"-Profil auch aufgehoben und auf 0..1 / 0..* gesetzt. Es sollte ein Hinweis weitere Regeln noch in der MII erarbeitet werden.

**Comment by julsas** [comment]
https://github.com/medizininformatik-initiative/kerndatensatzmodul-person/pull/24/commits/1f6203f927a67f30025db6bf3dd1d5314cac922e
https://github.com/medizininformatik-initiative/kerndatensatzmodul-person/pull/24/commits/5277182ddf89e65cec12946c3cb8ac382e612e86
