### ISSUE TITLE
MII-Reference auf Patient.identifier:pid.assigner sollte entfernt werden

### ISSUE THREAD

**Issue by alexzautke** [medizininformatik-initiative/kerndatensatzmodul-person#36]
Hier sollten wir fordern, dass assigner.identifier auf 1..1 MS gesetzt wird. Zudem sollte das CodeSystem https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.meta/1.0.3/files/319430 überarbeitet werden. Wie vor einiger Zeit angedacht könnten hier URLs verwendet anstatt Standort-Codes verwendet werden.

**Comment by julsas** [comment]
Aus TF üS: assigner.identifier sollte besser optional bleiben, weil Standorte nach Datenselektion und Extraktion nicht identifizierbar sein sollen.

Das CodeSystem sollte nach folgender Liste aktualisiert werden: https://confluence.imi.med.fau.de/pages/viewpage.action?pageId=246031654
