### ISSUE TITLE
[HDB-229] Spezifikation code.coding Element für Todesursache (Condition)

### ISSUE THREAD

**Issue by julsas** [medizininformatik-initiative/kerndatensatzmodul-person#55]
Im IG für das Condition Profil für die Todesursache ist für das Element code.coding lediglich die Terminologie ICD10-WHO spezifiziert. Es wäre sinnvoll, analog zum Condition Profil des Basismoduls Diagnose auch noch die Terminologien ICD10-GM und SNOMED anzugeben.

**Comment by jpwiedekopf** [comment]
Zur Todesursachencodierung ist die Verwendung von ICD-10-WHO vorgeschrieben. Eine Codierung in ICD-10-GM und/oder SCT wird in der Regel nicht in den Primärdaten vorliegen. Sollte dies doch vorliegen, ist eine Codierung mit anderen Code-Systems nicht verboten, da das Slicing `open` ist, und `code` mit Kardinalität `1..` spezifiziert ist.

**Comment by julsas** [comment]
Danke, die Antwort habe ich so weitergegeben.
