### ISSUE TITLE
CodeSystem for ICD-10-WHO missing

### ISSUE THREAD

**Issue by jpwiedekopf** [medizininformatik-initiative/kerndatensatzmodul-person#56]
The CodeSystem "ICD-10-WHO" (canonical `http://hl7.org/fhir/sid/icd-10`) is not represented in the package and not available in FHIR format on the Internet.

A strategy for converting the CodeSystem from the native format, or a placeholder CodeSystem should be created should converting the CodeSystem not be possible due to technical or license reasons (in this case, the CodeSystem and the ImplementationGuide should describe how to acquire the master file to implementers).

**Comment by jpwiedekopf** [comment]
There is a ClaML version from BfArM with German labels that would be easy to generate, but I'm not sure if assigning the canonical `http://hl7.org/fhir/sid/icd-10` would be appropriate here. Could we still change the canonical to e.g. `http://fhir.de/CodeSystem/bfarm/icd-10-who`?

**Comment by julsas** [comment]
Canonical must be `http://hl7.org/fhir/sid/icd-10` or it would clash with the profile.
